### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by lukliz** [UKPLab/EACL21-personalized-conversational-system#1]
Hi, 

when I run python ../convai_evaluation_edit.py
I am getting the following errors

**ModuleNotFoundError: No module named 'utils'**

I can't find utils.py in any of the folders.

Did I install something wrong, or is the utils file not uploaded?

Thanks in advance.

**Comment by MMesgar** [comment]
Hi, thanks for pointing this out. We added the file utils.py, best
