### ISSUE TITLE
ModuleNotFoundError: No module named 'file_utils'

### ISSUE THREAD

**Issue by lukliz** [UKPLab/EACL21-personalized-conversational-system#2]
Hi,

when I run python ./train.py
I am getting the following errors

**ModuleNotFoundError:  No module named 'file_utils'**

I can't find file_utils.py in any of the folders.

Is the utils file not uploaded?

Thanks in advance.

**Comment by MMesgar** [comment]
Thanks, can you send me the full message of the error?

**Comment by lukliz** [comment]
```
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from rl_utils import create_critic, f1_rewarder, bleu_rewarder, plot_reward, LinearRegressionModel, process_document, \
  File "/home/mscho/TODS/GPT2-based/EACL21-personalized-conversational-system/rl_utils.py", line 19, in <module>
    import file_utils
ModuleNotFoundError: No module named 'file_utils'
```

This is the full message of the error.

Thanks : )

**Comment by MMesgar** [comment]
Thanks! I added the file to the repo.
